
export type AssistedInterface = {
  id?: number,
  name: string,
  social_name?: string,
  mother_name?: string,
  father_name?: string,
  sex?: string,
  birth_data?: string,
  nationality?: string,
  phone_number?: string,
  city_residence?: string,
  rg?: string,
  org_e?: string,
  uf?: string,
  dt_e?: string,
  cpf?: string,
  reservist?: string,
  work_wallet?: string,
  birth_cert?: string,
  nis?: string,
  benefits?: string,
  situation: string,
  schooling?: string,
  relactory: string
}